### ISSUE TITLE
Head fixed hidden when using simultaneously filters option

### ISSUE THREAD

**Issue by JmiXIII** [paulhodel/jexcel#1487]
While working correctly without filters option, Head Fixed does not work when filters is enabled :

      tableOverflow: true,
      search: true,
      filters: true,
      tableHeight: "300px",

link -> https://codesandbox.io/s/jspreadsheet-forked-lh4xo

**Comment by GBonnaire** [comment]
Yes.

You need add on your CSS
```CSS
.jexcel > thead > tr:nth-child(2) > td {
  top: 24px;
}
```

**Comment by JmiXIII** [comment]
I've tried adding:
2 lines are now fixed : header + filter
But headers are transparent (can see the data scrolling instead of the columns name).
Any idea how to fix it ?

<style>
.jexcel > thead > tr > td:nth-child(1n+0) {
     top: 24px;
}
</style>

**Comment by GBonnaire** [comment]
Hi,

Good code is : 

```CSS
.jexcel > thead > tr:nth-child(2) > td {
  top: 24px;
}
```
