### ISSUE TITLE
Change background-color in range of cell.

### ISSUE THREAD

**Issue by ricardoperroni** [paulhodel/jexcel#1522]
Hi,

I need change "backgroud-color" for 100 cell element. Exists range function for this?

Thx

**Comment by GBonnaire** [comment]
Hi,

It's for all cell ?

If true, you can use CSS 
```CSS
     .jspreadsheet tr td {
          background-color: #XXXXXX;
     }
```

Otherwhise, you can use `updateTable` option in jspreadsheet
```javascript
var mySheet = jspreadsheet(DOMElement, {
      /* your configuration */
      updateTable: function(rootElement, cell, x, y, value, valueProcessed, cellName) {
               cell.style.backgroundColor = "#XXXXXX";
      }
});
```
