### ISSUE TITLE
Freeze column footer

### ISSUE THREAD

**Issue by ricardoperroni** [paulhodel/jexcel#1543]
Hi guys!

I have probelm with frozen for 3 columns, for example, in my footer table, on link above sugested change my css, unfortily doen's work...

Freeze column footer #1541
https://github.com/jspreadsheet/ce/issues/1541

Another idea?

Thx

**Comment by GBonnaire** [comment]
Hi,

How you want freeze, horizontale or verticale direction ?

If it's when in verticale move of all footer , you can use this CSS fix :
```CSS
.jexcel > tfoot > tr > td {
  position: sticky;
  left: 0px;
  z-index: 3 !important;
}
```

on horizontale move : 
```CSS
.jexcel > tfoot > tr > td {
  position: sticky;
  bottom: 0px;
  z-index: 3 !important;
}
```

After you can select number of colums with css property `:nth-child` like this 
```CSS
.jexcel > tfoot > tr > td:nth-child(1), .jexcel > tfoot > tr > td:nth-child(2) {
  position: sticky;
  left: 0px;
  z-index: 3 !important;
}
```
otherwise, better, you can add with JS, class `jexcel_freezed` on column in footer you want freeze (Example with nesterHeader : #1539 )
