### ISSUE TITLE
checkbox can be still changed for read only cells

### ISSUE THREAD

**Issue by Hypnos3** [paulhodel/jexcel#1575]
If a cell is set as readonly, it can be changed if the column type is 'checkbox' by clicking with the mouse on the checkbox. By keyboard the checkbox state can not be changed.
In such a case the events "onbeforechange", "onchange" are not fired.

**Comment by davidroeca** [comment]
Ran into this recently. Here's a workaround with CSS:

```css
.jexcel td.readonly input {
  pointer-events: none;
}
```
